name: iOS Simulator Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Brew update
        run: brew update

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build for iOS Simulator (no signing)
        run: |
          xcodebuild \
            -project FocusFlow.xcodeproj \
            -scheme FocusFlow \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: FocusFlow-sim-app
          path: build/Build/Products/Release-iphonesimulator/FocusFlow.app
